name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync to Hugging Face Hub
        uses: huggingface/hub-sync@v0.1.0
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          hf_repo_id: Qalam/Nuclear-Intelligence
          hf_repo_type: space
